spring:
  application:
   name: spring-chat-bot
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:9b
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
